name: 'Submodule Autosync Notification'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:   
  notify:
    name: 'Submodule Autosync Notification'
    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        subscribers: [Glitonea.DesktopApp]
        branches: [master]

    defaults:
      run:
        shell: bash

    steps:
    - name: Notify subscriber(s)
      uses: actions/github-script@v7.0.1
      with:
        retries: 3
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: ${{ matrix.subscribers }},
            workflow_id: 'submodule-autosync.yml'
            ref: ${{ matrix.branches }}
          })
      
